### ISSUE TITLE
fails when trying to be installed in jupyterlab 2.x

### ISSUE THREAD

**Issue by ludwig-nc** [itsjafer/jupyterlab-sparkmonitor#11]
Are the any plans of updating this extension to work with jupyterlab 2.x?

Currently the installation fails with a version conflict.

`ValueError: The extension "jupyterlab_sparkmonitor" does not yet support the current version of JupyterLab.`

**Comment by itsjafer** [comment]
It shouldn't be difficult; I'll look into this soon

**Comment by itsjafer** [comment]
Hi, I've made a change to introduce JupyterLab 2.0 compatibility so I'm going to go ahead and close this PR
