### ISSUE TITLE
Monitoring appears under wrong cell

### ISSUE THREAD

**Issue by oleksii-nikitchuk** [itsjafer/jupyterlab-sparkmonitor#14]
When I use shortcut Shift + Enter to run the current cell (C0) and select below one (C1), monitoring appears under currently selected cell (C1), but I expect to see it under C0.

**Comment by itsjafer** [comment]
Seems that using shift+enter does an execution followed by immediately selecting the next cell as active. I'll look into changing how the extension can attach to cells based one execution instead of using the 'active' cell.

**Comment by Ben-Epstein** [comment]
I've forked this repo and fixed the issue [here](https://github.com/Ben-Epstein/jupyterlab-sparkmonitor). My implementation also supports multiple spark sessions. If you'd like to merge just let me know :)

**Comment by itsjafer** [comment]
@Ben-Epstein for sure! Please make a PR and I’ll do a quick test/review and merge it in. I love open source :)

**Comment by Ben-Epstein** [comment]
@itsjafer  Me too! https://github.com/itsjafer/jupyterlab-sparkmonitor/pull/21
