### ISSUE TITLE
pyspark 3.0.0 support?

### ISSUE THREAD

**Issue by lhayhurst** [itsjafer/jupyterlab-sparkmonitor#23]
noticed this in setup.py

```
  install_requires=[
          'bs4',
          'tornado',
          'pyspark<3.0.0',
          'jupyterlab>=2.0.0'
      ],
```
Is there any reason why you've pinned to < 3.0.0 for pyspark? I'm in a 3.0.0 env.

Great tool ... hope I get to use it! Thank you! :-)

**Comment by itsjafer** [comment]
As it stands, the extension fails to run with pyspark 3 so I've pinned < 3 as a requirement. When I get time, I will be taking a look and what changes need to be made in order to migrate the extension to be compatible with newer versions of pyspark

**Comment by lhayhurst** [comment]
🆒  thank you for the quick reply. eagerly watching!

**Comment by ianferreira** [comment]
@itsjafer  can we help with Spark3 support, this is a great tool!

**Comment by footplus** [comment]
It seems that the changes needed are not so big if you just look to support Spark 3, the main issue is that StageInfo.attemptId() has been renamed to StageInfo.attemptNumber() inside Spark API (https://spark.apache.org/docs/2.4.0/api/java/org/apache/spark/scheduler/StageInfo.html). This change could be hidden inside the listener.jar component itself, by exporting the old attemptIds.

I did a quick ad-hoc patch here (but it will break the compatibility with some older Spark versions) https://gist.github.com/footplus/22339282854630698d0af88dd7488192 ; perhaps it may be of some use while designing a complete patch.

Also, the packages adds pyspark as a dependency, which may not be very practical if pyspark is already provided in some way (via setting PYTHONPATH e.g.) not understandable by pip (it results in installing Spark's jars twice, and less control over Spark versions).

**Comment by ianferreira** [comment]
Thanks much @footplus  we ended up getting it working on 3. Happy to PR back.

**Comment by yosit** [comment]
@ianferreira can you?

**Comment by 88manpreet** [comment]
@ianferreira Any plans on having this released?

**Comment by ianferreira** [comment]
@mtracy-core can you submit a PR

**Comment by mtracy-core** [comment]
@ianferreira will do. Will be submitting on my other public account. @millertracy

**Comment by itsjafer** [comment]
Hey everyone, sorry I’ve been so busy with school lately, I will happily review a PR when it’s made :)

**Comment by itsjafer** [comment]
This is now resolved. jupyterlab-sparkmonitor 4.X is now pyspark 3.X compatible cc: @ianferreira @88manpreet @yosit @lhayhurst. I implemented the solution proposed by @footplus, thank you for the contribution!
